// import localFont from "next/font/local";
import Head from "next/head";
import "./globals.css";
import Navbar from "@/components/shared/navbar/Navbar";


export const metadata = {
  title: "GreenGrowth",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
      <Navbar />
        {children}
      </body>
    </html>
  );
}
